# Generated by Django 5.2.17 on 2026-08-28 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(help_text='Somente números.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Informe o CPF com 11 dígitos, apenas números.')], verbose_name='CPF')),
                ('telefone_whatsapp', models.CharField(max_length=20, verbose_name='telefone / WhatsApp')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nome'],
            },
        ),
    ]
