# Generated by Django 5.2.17 on 2026-08-28 17:57

import apps.clientes.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(help_text='Somente números (11 dígitos).', max_length=11, unique=True, validators=[apps.clientes.models.valida_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_whatsapp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', verbose_name='telefone / WhatsApp'),
        ),
    ]
