# Generated by Django 5.2.17 on 2026-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf_alter_cliente_telefone_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarcado = arquivado (some da lista principal, mas o cadastro e o histórico de contratos/pagamentos continuam intactos).', verbose_name='ativo'),
        ),
    ]
