# Generated by Django 5.2.17 on 2026-09-03 16:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0003_contrato_proximo_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='nº da parcela')),
                ('data_vencimento', models.DateField(verbose_name='data de vencimento')),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor previsto')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor pago')),
                ('status', models.CharField(choices=[('aberto', 'Em aberto'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='aberto', max_length=10, verbose_name='status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vencimentos', to='contratos.contrato', verbose_name='contrato')),
            ],
            options={
                'verbose_name': 'vencimento',
                'verbose_name_plural': 'vencimentos',
                'ordering': ['contrato', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'numero'), name='vencimento_unico_por_contrato')],
            },
        ),
    ]
