# Generated by Django 5.2.17 on 2026-09-03 17:24

import apps.pagamentos.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_contrato_saldo_transportado'),
        ('pagamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='data do pagamento')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor pago')),
                ('forma', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='pix', max_length=10, verbose_name='forma de pagamento')),
                ('comprovante', models.FileField(blank=True, upload_to=apps.pagamentos.models.caminho_comprovante, verbose_name='comprovante')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='contratos.contrato', verbose_name='contrato')),
                ('usuario_baixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baixas', to=settings.AUTH_USER_MODEL, verbose_name='quem deu baixa')),
                ('vencimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='pagamentos.vencimento', verbose_name='parcela')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-data_pagamento', '-criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vencimento__isnull', False)), fields=('contrato', 'vencimento'), name='pagamento_unico_por_vencimento'), models.CheckConstraint(condition=models.Q(('valor_pago__gt', 0)), name='pagamento_valor_positivo')],
            },
        ),
    ]
