# Generated by Django 5.2.17 on 2026-09-09 17:49

import apps.pagamentos.models
import apps.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0005_rename_cobrancapix_cobrancacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(blank=True, upload_to=apps.pagamentos.models.caminho_comprovante, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), apps.validadores.validar_tamanho_upload], verbose_name='comprovante'),
        ),
    ]
