# Generated by Django 5.2.17 on 2026-09-25 18:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_alter_pagamento_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='juros_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opcional. Só registro — não conta como parcela: não abate o valor_previsto nem transporta saldo para a próxima parcela (o juros é um valor à parte, calculado por dia de atraso, e nunca muda o que se espera da parcela seguinte).', max_digits=10, verbose_name='juros recebidos'),
        ),
    ]
