# Generated by Django 5.2.17 on 2026-09-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0007_pagamento_juros_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='id_externo_codigo',
            field=models.CharField(blank=True, max_length=160, verbose_name='ID do copia-e-cola no provedor'),
        ),
        migrations.AddField(
            model_name='cobrancacora',
            name='duplicada',
            field=models.BooleanField(default=False, verbose_name='pago em duplicidade'),
        ),
        migrations.AddField(
            model_name='cobrancacora',
            name='duplicidade_resolvida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('lido', 'Lido'), ('erro', 'Erro'), ('cancelado', 'Cancelado'), ('apagado', 'Apagado do WhatsApp')], default='pendente', max_length=12),
        ),
    ]
