# Generated by Django 5.2.17 on 2026-09-27 00:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_ativo'),
        ('pagamentos', '0008_cobranca_apagada_e_pix_duplicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancacora',
            name='confirmacao_enviada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ComprovanteRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=160, unique=True, verbose_name='ID da mensagem no WhatsApp')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('documento', 'Documento/PDF')], max_length=12)),
                ('nome_arquivo', models.CharField(blank=True, max_length=200)),
                ('legenda', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando a Cora'), ('confirmado', 'Pix confirmado'), ('descartado', 'Descartado')], default='aguardando', max_length=12)),
                ('recebido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('resposta_enviada_em', models.DateTimeField(blank=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprovantes_recebidos', to='clientes.cliente')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vencimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprovantes_recebidos', to='pagamentos.vencimento')),
            ],
            options={
                'ordering': ['-recebido_em'],
            },
        ),
    ]
