# Generated by Django 5.2.17 on 2026-10-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0009_comprovantes_recebidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.TextField(verbose_name='QR code (data URI)')),
                ('gerado_em', models.DateTimeField(verbose_name='gerado em')),
            ],
            options={
                'verbose_name': 'QR code do WhatsApp',
                'verbose_name_plural': 'QR codes do WhatsApp',
            },
        ),
    ]
