# Generated by Django 5.2.17 on 2026-10-06 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0010_qr_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pausada', models.BooleanField(default=True, verbose_name='cobranças automáticas paradas')),
                ('iniciada_em', models.DateTimeField(blank=True, null=True, verbose_name='cobranças iniciadas em')),
                ('pausada_em', models.DateTimeField(blank=True, null=True, verbose_name='pausada em')),
                ('pausada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='pausada por')),
            ],
            options={
                'verbose_name': 'configuração de cobrança',
                'verbose_name_plural': 'configuração de cobrança',
            },
        ),
    ]
