# Generated by Django 5.2.17 on 2026-10-07 16:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0011_configuracao_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancacora',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
