# Generated by Django 5.2.17 on 2026-09-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_nome_e_email_obrigatorios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='claro', max_length=10, verbose_name='tema'),
        ),
    ]
