# Generated by Django 5.2.17 on 2026-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_tema_do_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='termos_aceitos_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='termos aceitos em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='termos_aceitos_versao',
            field=models.CharField(blank=True, max_length=20, verbose_name='versão dos termos aceita'),
        ),
    ]
