# Generated by Django 5.2.17 on 2026-08-28 17:57

import apps.contratos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf_alter_cliente_telefone_whatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(help_text='Diferencia contratos do mesmo cliente. Ex.: "iPhone 11".', max_length=80, verbose_name='apelido / descrição')),
                ('aparelho_modelo', models.CharField(max_length=120, verbose_name='aparelho (modelo)')),
                ('imei', models.CharField(blank=True, max_length=20, verbose_name='IMEI')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor total do contrato')),
                ('estrutura', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('dezena', 'Por dezena'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=12, verbose_name='estrutura de pagamento')),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor da parcela')),
                ('num_parcelas', models.PositiveIntegerField(blank=True, null=True, verbose_name='nº de parcelas')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('dia_referencia', models.CharField(blank=True, help_text='Ex.: quinzenal — data acordada com o Alisson.', max_length=40, verbose_name='dia(s) de referência')),
                ('fiador', models.CharField(blank=True, max_length=150, verbose_name='fiador / avalista')),
                ('status', models.CharField(choices=[('em_dia', 'Em dia'), ('atrasado', 'Atrasado'), ('inadimplente', 'Inadimplente'), ('quitado', 'Quitado')], default='em_dia', max_length=12, verbose_name='status')),
                ('data_prevista_quitacao', models.DateField(blank=True, null=True, verbose_name='data prevista de quitação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['cliente__nome', 'apelido'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato_assinado', 'Contrato assinado'), ('rg', 'RG / documento de identidade'), ('comprovante_residencia', 'Comprovante de residência'), ('outro', 'Outro')], default='outro', max_length=24, verbose_name='tipo')),
                ('arquivo', models.FileField(upload_to=apps.contratos.models.caminho_documento, verbose_name='arquivo')),
                ('descricao', models.CharField(blank=True, max_length=150, verbose_name='descrição')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='enviado em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contratos.contrato', verbose_name='contrato')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'documento do contrato',
                'verbose_name_plural': 'documentos do contrato',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
