# Generated by Django 5.2.17 on 2026-09-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='fiador',
        ),
    ]
