# Generated by Django 5.2.17 on 2026-09-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_remove_contrato_fiador'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='proximo_vencimento',
            field=models.DateField(blank=True, help_text='Data da próxima parcela a receber. Manual por enquanto; a Fase 2 vai gerar os vencimentos automaticamente. É a base do cálculo de atraso.', null=True, verbose_name='próximo vencimento'),
        ),
    ]
