# Generated by Django 5.2.17 on 2026-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contrato_proximo_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_prevista_quitacao',
            field=models.DateField(blank=True, help_text='Calculada pelo sistema (data da última parcela) quando há valor e nº de parcelas.', null=True, verbose_name='data prevista de quitação'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dia_referencia',
            field=models.CharField(blank=True, help_text='Anotação livre (ex.: quinzenal — data combinada com o Alisson). Não entra no cálculo.', max_length=40, verbose_name='dia(s) de referência'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='proximo_vencimento',
            field=models.DateField(blank=True, help_text='Data da próxima parcela a receber — base do cálculo de atraso e juros. Continua manual; ligá-la à parcela em aberto é da Fase 4.', null=True, verbose_name='próximo vencimento'),
        ),
    ]
