# Generated by Django 5.2.17 on 2026-09-03 17:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_alter_contrato_data_prevista_quitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='saldo_transportado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo de um pagamento parcial (positivo = ainda devido; negativo = crédito) que não teve parcela em aberto seguinte onde cair. É somado à próxima parcela gerada por gerar_vencimentos(). Fase 3.', max_digits=10, verbose_name='saldo transportado'),
        ),
    ]
