# Generated by Django 5.2.17 on 2026-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_contrato_quitado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='proximo_vencimento',
            field=models.DateField(blank=True, help_text='Data da próxima parcela a receber. Usada no cálculo de atraso e juros só enquanto o contrato não tem vencimentos gerados (Vencimento) — depois disso quem manda é a parcela em aberto mais antiga.', null=True, verbose_name='próximo vencimento'),
        ),
    ]
