# Generated by Django 5.2.17 on 2026-09-09 17:49

import apps.contratos.models
import apps.validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_contrato_proximo_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocontrato',
            name='arquivo',
            field=models.FileField(upload_to=apps.contratos.models.caminho_documento, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), apps.validadores.validar_tamanho_upload], verbose_name='arquivo'),
        ),
    ]
