# Generated by Django 5.2.17 on 2026-10-01

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contratos", "0009_contrato_aparelho")]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="juros_diario",
            field=models.DecimalField(decimal_places=2, default=Decimal("5.00"), help_text="Cobrado por dia de atraso neste contrato.", max_digits=8, verbose_name="juros diário"),
        ),
    ]
