# Generated by Django 5.2.17 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("contratos", "0010_contrato_juros_diario")]

    operations = [
        migrations.CreateModel(
            name="ImportacaoContratoPendente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dados", models.JSONField()),
                ("problemas", models.JSONField(default=list)),
                ("linha_origem", models.PositiveIntegerField()),
                ("resolvida_em", models.DateTimeField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={"verbose_name": "pendência de importação", "verbose_name_plural": "pendências de importação", "ordering": ["criada_em", "linha_origem"]},
        ),
    ]
