# Generated by Django 5.2.17 on 2026-10-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0011_importacaocontratopendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cadastro_confirmacao',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
