# Generated by Django 5.2.17 on 2026-10-06 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparelhos', '0001_initial'),
        ('contratos', '0012_contrato_cadastro_confirmacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='aparelho',
            field=models.OneToOneField(blank=True, help_text='Opcional — vincula a um aparelho já cadastrado no estoque, que passa a aparecer como alocado. Sem isso, modelo e IMEI acima ficam só como texto, sem controle de estoque.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='aparelhos.aparelho', verbose_name='aparelho do estoque'),
        ),
    ]
