# Generated by Django 5.2.17 on 2026-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_aparelho_help_text_alocado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='estrutura',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=12, verbose_name='estrutura de pagamento'),
        ),
    ]
