# Generated by Django 5.2.17 on 2026-10-09 15:54

from django.db import migrations, models


def guardar_dia_de_referencia_nas_observacoes(apps, schema_editor):
    """O antigo "dia de referência" era uma anotação livre; não se perde: vai para as observações."""
    Contrato = apps.get_model("contratos", "Contrato")
    for contrato in Contrato.objects.exclude(dia_referencia=""):
        nota = f"Dia de referência (anotação antiga): {contrato.dia_referencia}"
        contrato.observacoes = f"{contrato.observacoes}\n{nota}".strip()
        contrato.save(update_fields=["observacoes"])


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_estrutura_so_semanal_quinzenal_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='dias_cobranca_mes',
            field=models.CharField(blank=True, help_text='Mensal: o dia (ex.: "15"). Quinzenal em dois dias fixos: "5,20". Vazio nos demais.', max_length=5, verbose_name='dia(s) do mês da cobrança'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='primeira_cobranca',
            field=models.DateField(blank=True, help_text='Data da parcela 1. As demais seguem o dia de cobrança (dia da semana ou do mês). Vazio nos contratos antigos, que contam a partir da data da compra.', null=True, verbose_name='primeira cobrança'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='apelido',
            field=models.CharField(help_text='Para diferenciar os contratos do mesmo cliente. Ex.: "iPhone 11".', max_length=80, verbose_name='nome do contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(verbose_name='data da compra'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estrutura',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=12, verbose_name='frequência de pagamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='num_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantidade de parcelas'),
        ),
        migrations.RunPython(guardar_dia_de_referencia_nas_observacoes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contrato',
            name='dia_referencia',
        ),
    ]
