# Generated by Django 5.2.17 on 2026-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Ex.: "iPhone 11 64GB".', max_length=120, verbose_name='modelo')),
                ('imei', models.CharField(blank=True, help_text='15 dígitos. Opcional, mas evita cadastrar o mesmo aparelho duas vezes.', max_length=20, null=True, unique=True, verbose_name='IMEI')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, help_text='Uso interno — não aparece para o cliente nem no contrato.', max_digits=10, null=True, verbose_name='custo de compra')),
                ('fornecedor', models.CharField(blank=True, max_length=120, verbose_name='fornecedor')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='data da compra')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'aparelho',
                'verbose_name_plural': 'aparelhos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
